<?xml version="1.0"?>

<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Robot Parameters -->
    <xacro:property name="PI" value="3.14159265"/>
    <xacro:property name="body_length" value="0.18"/>
    <xacro:property name="body_width" value="0.17"/>
    <xacro:property name="body_height" value="0.01"/>
    <xacro:property name="body_density" value="7850.0"/> <!-- Steel -->
    <xacro:property name="body_mass" value="${body_density * body_length * body_height * body_width}"/>
    <xacro:property name="body_inertia_x" value="${1.0/12.0 * body_mass * (body_height*body_height + body_width*body_width)}"/>
    <xacro:property name="body_inertia_y" value="${1.0/12.0 * body_mass * (body_length*body_length + body_height*body_height)}"/>
    <xacro:property name="body_inertia_z" value="${1.0/12.0 * body_mass * (body_length*body_length + body_width*body_width)}"/>

    <xacro:property name="wheel_radius" value="0.04"/>
    <xacro:property name="wheel_width" value="0.015"/>
    <xacro:property name="wheel_separation" value="${body_width + wheel_width}"/>
    <xacro:property name="wheel_offset" value="${body_length/2 - wheel_radius}"/>
    <xacro:property name="wheel_density" value="900"/> <!-- Ruber -->
    <xacro:property name="wheel_mass" value="${wheel_density * PI * wheel_radius * wheel_radius * wheel_width}"/>
    <xacro:property name="wheel_inertia_x" value="${1.0/12.0 * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
    <xacro:property name="wheel_inertia_y" value="${1.0/12.0 * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
    <xacro:property name="wheel_inertia_z" value="${1.0/2.0 * wheel_mass * wheel_radius * wheel_radius}"/>

    <xacro:property name="caster_radius" value="0.0125"/>
    <xacro:property name="caster_offset" value="${body_length/2 - caster_radius}"/>
    <xacro:property name="caster_density" value="0.1"/>
    <xacro:property name="caster_mass" value="${caster_density * 4.0/3.0 * PI * caster_radius * caster_radius * caster_radius}"/>
    <xacro:property name="caster_inertia_x" value="${2.0/5.0 * caster_mass * caster_radius * caster_radius}"/>
    <xacro:property name="caster_inertia_y" value="${2.0/5.0 * caster_mass * caster_radius * caster_radius}"/>
    <xacro:property name="caster_inertia_z" value="${2.0/5.0 * caster_mass * caster_radius * caster_radius}"/>

    <!-- Control Parameters -->    
    <xacro:property name="max_linear_acceleration" value="10"/>

    <!-- Links -->

    <!-- Body Link -->
    <link name="body_link">
        <inertial>
        <origin
            xyz="-0.0284 0 -0.008"
            rpy="0 0 0" />
        <mass
            value="0.300" />
        <inertia
            ixx="0.000290930982603083"
            ixy="2.96592562996834E-10"
            ixz="-4.89953593135407E-06"
            iyy="0.000293366944607641"
            iyz="-1.24079970534305E-11"
            izz="0.000578469246893076" />
        </inertial>
        <visual>
            <origin
                xyz="0 0 0"
                rpy="0 0 0" />
            <geometry>
                <mesh
                filename="package://gazebo_differential_drive_robot/meshes/base_link.STL" />
            </geometry>
            <material
                name="">
                <color
                rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
            </material>
        </visual>
        <collision>
            <origin
                xyz="0 0 0"
                rpy="0 0 0" />
            <geometry>
                <box size="0.18 0.17 0.03" />
            </geometry>
        </collision>
    </link>

    <!-- Left Wheel -->
    <link name="left_wheel_link">
        <inertial>
        <origin
            xyz="0 0 0.00808"
            rpy="0 0 0" />
        <mass
            value="0.015" />
        <inertia
            ixx="1.23422492282635E-06"
            ixy="-1.48859597124639E-10"
            ixz="3.30647721519471E-16"
            iyy="1.23431714543936E-06"
            iyz="-6.17403432705978E-16"
            izz="2.19640206701058E-06" />
        </inertial>
        <visual>
        <origin
            xyz="0 0 0"
            rpy="0 0 0" />
        <geometry>
            <mesh
            filename="package://gazebo_differential_drive_robot/meshes/left_wheel_link.STL" />
        </geometry>
        <material
            name="">
            <color
            rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
        </material>
        </visual>
        <collision>
            <origin
                xyz="0 0 0"
                rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.02" length="0.015"/>
            </geometry>
        </collision>
    </link>

    <!-- Right Wheel -->
    <link name="right_wheel_link">
        <inertial>
        <origin
            xyz="0 0 0.00808"
            rpy="0 0 0" />
        <mass
            value="0.015" />
        <inertia
            ixx="1.23422492920575E-06"
            ixy="1.48861577857816E-10"
            ixz="4.91594534149496E-16"
            iyy="1.23431713905996E-06"
            iyz="4.98850564443408E-16"
            izz="2.19640206701057E-06" />
        </inertial>
        <visual>
        <origin
            xyz="0 0 0"
            rpy="0 0 0" />
        <geometry>
            <mesh
            filename="package://gazebo_differential_drive_robot/meshes/right_wheel_link.STL" />
        </geometry>
        <material
            name="">
            <color
            rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
        </material>
        </visual>
        <collision>
        <origin
            xyz="0 0 0"
            rpy="0 0 0" />
        <geometry>
            <cylinder radius="0.02" length="0.015"/>
        </geometry>
        </collision>
    </link>

    <!-- Caster Wheel -->
    <link name="caster_link">
        <inertial>
            <origin
                xyz="0.0 0 0.0"
                rpy="-1.5707963267949 0 0" />
            <mass
                value="0.0669259238391975" />
            <inertia
                ixx="4.31779290240967E-06"
                ixy="3.54080995565633E-23"
                ixz="-7.16933357795495E-22"
                iyy="4.31779290240967E-06"
                iyz="6.61721086913841E-23"
                izz="4.31779290240967E-06" />
        </inertial>
        <visual>
            <origin
                xyz="0 0 0"
                rpy="0 0 0" />
            <geometry>
                <mesh
                filename="package://gazebo_differential_drive_robot/meshes/castor_wheel_xz_link.STL" />
            </geometry>
            <material
                name="">
                <color
                rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin
                xyz="0.0 0 -0.0"
                rpy="0 0 0" />
            <geometry>
                <sphere radius=".0125" />
            </geometry>
        </collision>
    </link>

    <!-- Joints -->

    <!-- Left Wheel Joint -->
    <joint name="left_wheel_joint" type="continuous">
        <origin
            xyz="-0.0775 0.0925 -0.02"
            rpy="-1.5707963267949 0 0" />
        <parent
            link="body_link" />
        <child
            link="left_wheel_link" />
        <axis
            xyz="0 0 1" />
        <limit
            effort="3"
            velocity="5" />
        <dynamics
            friction="0.1" />
    </joint>

    <!-- Right Wheel Joint -->
    <joint name="right_wheel_joint" type="continuous">
        <origin
            xyz="-0.0775 -0.0925 -0.02"
            rpy="-1.5707963267949 0 -3.1415926535898" />
        <parent
            link="body_link" />
        <child
            link="right_wheel_link" />
        <axis
            xyz="0 0 -1" />
        <limit
            effort="3"
            velocity="5" />
        <dynamics
            friction="0.1" />
    </joint>

    <!-- Caster Wheel Joint (fixed) -->
    <joint name="caster_joint" type="fixed">
        <origin
            xyz="0.07075 0 -0.0125"
            rpy="-1.5707963267949 0 0" />
        <parent link="body_link"/>
        <child link="caster_link"/>
    </joint>

    <!-- Gazebo Parameters -->
    <gazebo reference="body_link">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>

    <gazebo reference="right_wheel_link">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>

    <gazebo reference="left_wheel_link">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>

    <gazebo reference="caster_link">
        <mu1>0.000001</mu1>
        <mu2>0.000001</mu2>
    </gazebo>

    <!-- Gazebo Plugins -->
    <gazebo>
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <right_joint>right_wheel_joint</right_joint>
            <left_joint>left_wheel_joint</left_joint>
            <wheel_separation>${wheel_separation}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <max_linear_acceleration>${max_linear_acceleration}</max_linear_acceleration>
            <odom_publish_frequency>100</odom_publish_frequency>
            <topic>cmd_vel</topic>
            <odom_topic>odom</odom_topic>
        </plugin>

        <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic>
            <joint_name>right_wheel_joint</joint_name>
            <joint_name>left_wheel_joint</joint_name>
        </plugin>
    </gazebo>

</robot>
